use crate::ast::{Page, Project};
use crate::CompileError;

/// Phase C3 — stub. Full implementation in Phase C3.
pub fn emit_page(_project: &Project, page: &Page) -> Result<String, CompileError> {
    let component = crate::project::page_component_name(&page.path);
    Ok(format!(
        r#"// Page: {title} ({path}) — generated by VisuAlis
// Full component tree emit is Phase C3.
export default function {component}() {{
  return <div data-page="{path}" />;
}}
"#,
        title = page.title,
        path = page.path,
    ))
}

pub fn page_file_name(page: &Page) -> String {
    format!("{}.tsx", crate::project::page_component_name(&page.path))
}
