use crate::ast::Project;
use crate::workspace::Workspace;
use crate::CompileError;
use std::path::PathBuf;

/// Scaffold the static project files (package.json, vite, tsconfig, etc.).
/// Phase C4 — full page/action routing wired here.
pub fn scaffold(project: &Project, ws: &mut Workspace) -> Result<(), CompileError> {
    ws.insert_text(PathBuf::from("package.json"), package_json(project));
    ws.insert_text(PathBuf::from("vite.config.ts"), vite_config());
    ws.insert_text(PathBuf::from("tsconfig.json"), tsconfig());
    ws.insert_text(PathBuf::from("index.html"), index_html(project));
    ws.insert_text(PathBuf::from("src/main.tsx"), main_tsx());
    ws.insert_text(PathBuf::from("src/App.tsx"), app_tsx(project));
    ws.insert_text(PathBuf::from("src/styles.css"), styles_css());
    ws.insert_text(PathBuf::from("README.md"), readme(project));
    Ok(())
}

fn package_json(project: &Project) -> String {
    let name = slug(&project.name);
    format!(
        r#"{{
  "name": "{name}",
  "version": "{version}",
  "private": true,
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "tsc --noEmit && vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.27.0"
  }},
  "devDependencies": {{
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@vitejs/plugin-react": "^4.3.4",
    "typescript": "^5.6.0",
    "vite": "^6.0.0"
  }}
}}
"#,
        version = project.version
    )
}

fn vite_config() -> String {
    r#"import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({ plugins: [react()] });
"#
    .to_string()
}

fn tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2022", "DOM"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "skipLibCheck": true
  },
  "include": ["src"]
}
"#
    .to_string()
}

fn index_html(project: &Project) -> String {
    format!(
        r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
"#,
        project.name
    )
}

fn main_tsx() -> String {
    // Use ## delimiter because the content contains "#
    r##"import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";
import "./styles.css";

const root = document.getElementById("root");
if (!root) throw new Error("root element not found");

createRoot(root).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>,
);
"##
    .to_string()
}

fn app_tsx(project: &Project) -> String {
    let mut imports = String::new();
    let mut routes = String::new();

    for page in &project.pages {
        let component = page_component_name(&page.path);
        imports.push_str(&format!(
            "import {component} from \"./pages/{component}\";\n"
        ));
        routes.push_str(&format!(
            "      <Route path=\"{}\" element={{<{component} />}} />\n",
            page.path
        ));
    }

    // Default redirect to first page
    let first_path = project
        .pages
        .first()
        .map(|p| p.path.as_str())
        .unwrap_or("/");

    format!(
        r#"import {{ Routes, Route, Navigate }} from "react-router-dom";
{imports}
export default function App() {{
  return (
    <Routes>
{routes}      <Route path="*" element={{<Navigate to="{first_path}" replace />}} />
    </Routes>
  );
}}
"#
    )
}

fn styles_css() -> String {
    r#"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: system-ui, sans-serif; }
"#
    .to_string()
}

fn readme(project: &Project) -> String {
    format!(
        r#"# {}

Generated by VisuAlis.

## Run

```sh
npm install
npm run dev      # development server
npm run build    # production build → dist/
```
"#,
        project.name
    )
}

pub fn page_component_name(path: &str) -> String {
    let parts: Vec<&str> = path.split('/').filter(|s| !s.is_empty()).collect();
    if parts.is_empty() {
        return "Index".to_string();
    }
    parts
        .iter()
        .map(|s| {
            let mut c = s.chars();
            match c.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

fn slug(name: &str) -> String {
    name.to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '-' { c } else { '-' })
        .collect::<String>()
        .trim_matches('-')
        .to_string()
}
